cadence: bimonthly
label: CHURN_LABEL_14_DAY
features:
  - LIFETIME_DAY
  - MALES_PER_100_FEMALES
  - HH_MEAN_INCOME
  - HH_MEDIAN_INCOME
  - AGE_MEDIAN
  - AVG_HOUSEHOLD_SIZE
  - MARRIED_HH
  - SINGLE_MALE_HH
  - TOTAL_NET_REVENUE
  - ORDER_COUNT
  - DAYS_SINCE_LAST_ORDER
  - PAID_SOCIAL
  - PAID_SEARCH
  - REFERRAL
  - AFFILIATE
  - ORGANIC_SOCIAL
  - ORGANIC_SEARCH
  - MAIN_SITE
