cadence: bimonthly
churn_window_days: 14
features:
  - cycles_completed
  - is_active
  - days_since_created
  - days_to_next_order
  - updated_recently
filters:
  status: active
  frequency: 60d
timestamp_column: event_time
label_column: churn_label_14d